<?php

declare(strict_types=1);

return [
    'paths' => [
        // `__DIR__` means the public web root (set by entrypoint via PWS_BASE_DIR).
        'base_dir' => '__DIR__',
        // Keep config/src outside of the served directory.
        'src_dir' => '../../src',
    ],
    'ui' => [
        'css_base' => 'assets/css/base.css',
        'css_themes' => [
            'bright' => 'assets/css/theme-bright.css',
            'dark' => 'assets/css/theme-dark.css',
        ],
        'default_theme' => 'bright',
        // Supported: "24h" (default) or "12h".
        'time_format' => '24h',
        // Browser polling interval for latest values when API polling is used.
        'poll_interval_seconds' => 15,
        // Keep MQTT reconnects calm during transient broker/network outages.
        'mqtt_reconnect_delay_ms' => 10000,
        'css_custom' => '',
        // "auto" selects the highest plotly-*.min.js found in public/assets/vendor.
        'plotly_js' => 'auto',
        'plotly_wind_rose' => true,
        // Optional mapping for battery status-like integer values (0,1,5,9,...).
        'battery_status_labels' => [
            '0' => 'Normal',
            '1' => 'Low',
            '2' => 'Low',
            '3' => 'Critical',
            '4' => 'Critical',
            '5' => 'OK',
            '9' => 'Low',
        ],
        'sensor_thresholds' => [
            'air_quality' => [
                // Default alert threshold for air quality-related sensors. The
                // dashboard currently applies this to PM2.5-style metrics first.
                'alert_level' => 75,
            ],
            'soil_moisture' => [
                // Default out-of-range markers; adjust per installation.
                'low' => 20,
                'high' => 80,
            ],
        ],
        // Layout controls for all standard charts.
        'layout' => [
            'graph_max_columns' => 3,
            'graph_min_width_px' => 320,
            'graph_height_px' => 260,
            // Wind rose keeps its own row/size for readability.
            'wind_rose_height_px' => 380,
        ],
        'graphs' => [
            'temp_outside' => true,
            'temp_inside' => true,
            'humidity_outside' => true,
            'humidity_inside' => true,
            'wind_speed' => true,
            'wind_direction' => true,
            'pressure' => true,
            'rain_rate_hourly' => true,
            'rain_total_duration' => true,
            'feels_like' => true,
            'solar' => true,
            'cloudbase' => true,
            'et' => true,
            'sunshine' => true,
            'windrun' => true,
            'pm25' => true,
            'lightning' => true,
            'wind_rose' => true,
            'battery_wind' => true,
            'battery_rain' => true,
            'battery_lightning' => true,
            'battery_pm25' => true,
            'battery_indoor' => true,
        ],
    ],
    'location' => [
        // Required for sunrise/sunset and moonrise/moonset calculations.
        'latitude' => 0.0,
        'longitude' => 0.0,
        'timezone' => 'UTC',
    ],
    'forecast' => [
        // Supported providers: "wu", "openweather", or "none".
        'provider' => 'wu',
        // Optional multi-provider mode: list one or both ('wu', 'openweather').
        // If set, this overrides 'provider' selection for fetching/reading.
        'providers' => [],
        // Optional provider preference when multiple providers are enabled.
        'preferred_hourly_provider' => '',
        'preferred_daily_provider' => '',
        'alerts_provider' => 'openweather',
        'cache_ttl_seconds' => 900,
        'hourly_cache_ttl_seconds' => 14400,
        'alerts_cache_ttl_seconds' => 1800,
        // 1800s ~= 48 calls/day with single-call providers (keeps under 50/day).
        'refresh_interval_seconds' => 1800,
        'cache_table' => 'pws_wu_forecast_cache',
        'dashboard_hours' => 5,
        'wu_base_url' => 'https://api.weather.com',
        'wu_api_key' => 'CHANGE_ME',
        // Disable hourly fetch when subscription only includes daily forecast.
        'wu_hourly_enabled' => true,
        'wu_units' => 'm',
        'wu_language' => 'en-US',
        // Leave at 0.0 to inherit from location.latitude/location.longitude.
        'wu_latitude' => 0.0,
        'wu_longitude' => 0.0,
        // Valid values are API-defined durations such as "2day" or "15day".
        'wu_hourly_duration' => '2day',
        'wu_daily_duration_days' => 10,
        // OpenWeather provider config.
        // Mode: "onecall_3" (paid) or "free_5d" (free 3-hour forecast endpoint).
        'owm_mode' => 'onecall_3',
        'owm_base_url' => 'https://api.openweathermap.org',
        'owm_api_key' => 'CHANGE_ME',
        'owm_units' => 'metric',
        'owm_language' => 'en',
        // Leave at 0.0 to inherit location.latitude/location.longitude.
        'owm_latitude' => 0.0,
        'owm_longitude' => 0.0,
    ],
    'prediction' => [
        // Prediction cache generated by cron/CLI job.
        'cache_table' => 'pws_prediction_cache',
        'refresh_interval_seconds' => 1800,
        'horizons_hours' => [1, 3, 6, 12, 24],
    ],
    'optional_metric_groups' => [
        // Optional groups stay disabled by default. Users can enable whole groups
        // or override labels per metric in config.local.php without editing PHP.
        'extra_temperature' => [
            'enabled' => false,
            'metrics' => [
                'extraTemp1' => ['label' => 'Extra Temperature 1', 'unit' => 'temperature'],
                'extraTemp2' => ['label' => 'Extra Temperature 2', 'unit' => 'temperature'],
                'extraTemp3' => ['label' => 'Extra Temperature 3', 'unit' => 'temperature'],
                'extraTemp4' => ['label' => 'Extra Temperature 4', 'unit' => 'temperature'],
                'extraTemp5' => ['label' => 'Extra Temperature 5', 'unit' => 'temperature'],
                'extraTemp6' => ['label' => 'Extra Temperature 6', 'unit' => 'temperature'],
                'extraTemp7' => ['label' => 'Extra Temperature 7', 'unit' => 'temperature'],
                'extraTemp8' => ['label' => 'Extra Temperature 8', 'unit' => 'temperature'],
            ],
        ],
        'extra_humidity' => [
            'enabled' => false,
            'metrics' => [
                'extraHumid1' => ['label' => 'Extra Humidity 1', 'unit' => 'humidity'],
                'extraHumid2' => ['label' => 'Extra Humidity 2', 'unit' => 'humidity'],
                'extraHumid3' => ['label' => 'Extra Humidity 3', 'unit' => 'humidity'],
                'extraHumid4' => ['label' => 'Extra Humidity 4', 'unit' => 'humidity'],
                'extraHumid5' => ['label' => 'Extra Humidity 5', 'unit' => 'humidity'],
                'extraHumid6' => ['label' => 'Extra Humidity 6', 'unit' => 'humidity'],
                'extraHumid7' => ['label' => 'Extra Humidity 7', 'unit' => 'humidity'],
                'extraHumid8' => ['label' => 'Extra Humidity 8', 'unit' => 'humidity'],
            ],
        ],
        'generic_battery_status' => [
            'enabled' => false,
            'metrics' => [
                'batteryStatus1' => ['label' => 'Channel 1 Batt', 'unit' => 'status'],
                'batteryStatus2' => ['label' => 'Channel 2 Batt', 'unit' => 'status'],
                'batteryStatus3' => ['label' => 'Channel 3 Batt', 'unit' => 'status'],
                'batteryStatus4' => ['label' => 'Channel 4 Batt', 'unit' => 'status'],
                'batteryStatus5' => ['label' => 'Channel 5 Batt', 'unit' => 'status'],
                'batteryStatus6' => ['label' => 'Channel 6 Batt', 'unit' => 'status'],
                'batteryStatus7' => ['label' => 'Channel 7 Batt', 'unit' => 'status'],
                'batteryStatus8' => ['label' => 'Channel 8 Batt', 'unit' => 'status'],
            ],
        ],
        'co2_family' => [
            'enabled' => false,
            'metrics' => [
                'co2' => ['label' => 'CO2', 'unit' => 'ppm'],
                'co2_Hum' => ['label' => 'CO2 Sensor Humidity', 'unit' => 'humidity'],
                'co2_Temp' => ['label' => 'CO2 Sensor Temperature', 'unit' => 'temperature'],
                'co2in' => ['label' => 'Indoor CO2', 'unit' => 'ppm'],
                'co2_Batt' => ['label' => 'CO2 Sensor Battery', 'unit' => 'status'],
            ],
        ],
        'leaf_sensors' => [
            'enabled' => false,
            'metrics' => [
                'leafTemp1' => ['label' => 'Leaf Temperature 1', 'unit' => 'temperature'],
                'leafTemp2' => ['label' => 'Leaf Temperature 2', 'unit' => 'temperature'],
                'leafWet1' => ['label' => 'Leaf Wetness 1', 'unit' => 'index'],
                'leafWet2' => ['label' => 'Leaf Wetness 2', 'unit' => 'index'],
                'leafWet3' => ['label' => 'Leaf Wetness 3', 'unit' => 'index'],
                'leafWet4' => ['label' => 'Leaf Wetness 4', 'unit' => 'index'],
                'leafWet5' => ['label' => 'Leaf Wetness 5', 'unit' => 'index'],
                'leafWet6' => ['label' => 'Leaf Wetness 6', 'unit' => 'index'],
                'leafWet7' => ['label' => 'Leaf Wetness 7', 'unit' => 'index'],
                'leafWet8' => ['label' => 'Leaf Wetness 8', 'unit' => 'index'],
                'leafWetBatt1' => ['label' => 'Leaf Wetness Batt 1', 'unit' => 'status'],
                'leafWetBatt2' => ['label' => 'Leaf Wetness Batt 2', 'unit' => 'status'],
                'leafWetBatt3' => ['label' => 'Leaf Wetness Batt 3', 'unit' => 'status'],
                'leafWetBatt4' => ['label' => 'Leaf Wetness Batt 4', 'unit' => 'status'],
                'leafWetBatt5' => ['label' => 'Leaf Wetness Batt 5', 'unit' => 'status'],
                'leafWetBatt6' => ['label' => 'Leaf Wetness Batt 6', 'unit' => 'status'],
                'leafWetBatt7' => ['label' => 'Leaf Wetness Batt 7', 'unit' => 'status'],
                'leafWetBatt8' => ['label' => 'Leaf Wetness Batt 8', 'unit' => 'status'],
            ],
        ],
        'leak_sensors' => [
            'enabled' => false,
            'metrics' => [
                'leak_1' => ['label' => 'Leak Sensor 1', 'unit' => 'state'],
                'leak_2' => ['label' => 'Leak Sensor 2', 'unit' => 'state'],
                'leak_3' => ['label' => 'Leak Sensor 3', 'unit' => 'state'],
                'leak_4' => ['label' => 'Leak Sensor 4', 'unit' => 'state'],
                'leak_Batt1' => ['label' => 'Leak Sensor Batt 1', 'unit' => 'status'],
                'leak_Batt2' => ['label' => 'Leak Sensor Batt 2', 'unit' => 'status'],
                'leak_Batt3' => ['label' => 'Leak Sensor Batt 3', 'unit' => 'status'],
                'leak_Batt4' => ['label' => 'Leak Sensor Batt 4', 'unit' => 'status'],
            ],
        ],
        'hail_sensors' => [
            'enabled' => false,
            'metrics' => [
                'hail' => ['label' => 'Hail', 'unit' => 'rain'],
                'hailRate' => ['label' => 'Hail Rate', 'unit' => 'rain_rate'],
                'hailDur' => ['label' => 'Hail Duration', 'unit' => 'seconds'],
                'hailBatteryStatus' => ['label' => 'Hail Battery', 'unit' => 'status'],
            ],
        ],
        'snow_sensors' => [
            'enabled' => false,
            'metrics' => [
                'snow' => ['label' => 'Snow', 'unit' => 'rain'],
                'snowDepth' => ['label' => 'Snow Depth', 'unit' => 'mm'],
                'snowMoisture' => ['label' => 'Snow Moisture', 'unit' => 'percent'],
                'snowRate' => ['label' => 'Snow Rate', 'unit' => 'rain_rate'],
                'snowBatteryStatus' => ['label' => 'Snow Battery', 'unit' => 'status'],
            ],
        ],
        'particulates_extended' => [
            'enabled' => false,
            'metrics' => [
                'pm1_0' => ['label' => 'PM1.0', 'unit' => 'ugm3'],
                'pm4_0' => ['label' => 'PM4.0', 'unit' => 'ugm3'],
                'pm10_0' => ['label' => 'PM10.0', 'unit' => 'ugm3'],
                'pm25_1' => ['label' => 'PM2.5 Sensor 1', 'unit' => 'ugm3'],
                'pm25_2' => ['label' => 'PM2.5 Sensor 2', 'unit' => 'ugm3'],
                'pm25_3' => ['label' => 'PM2.5 Sensor 3', 'unit' => 'ugm3'],
                'pm25_4' => ['label' => 'PM2.5 Sensor 4', 'unit' => 'ugm3'],
                'pm25_Batt2' => ['label' => 'PM2.5 Batt 2', 'unit' => 'status'],
                'pm25_Batt3' => ['label' => 'PM2.5 Batt 3', 'unit' => 'status'],
                'pm25_Batt4' => ['label' => 'PM2.5 Batt 4', 'unit' => 'status'],
            ],
        ],
        'lightning_extended' => [
            'enabled' => false,
            'metrics' => [
                'lightning_distance' => ['label' => 'Lightning Distance', 'unit' => 'km'],
                'lightning_disturber_count' => ['label' => 'Lightning Disturber Count', 'unit' => 'count'],
                'lightning_energy' => ['label' => 'Lightning Energy', 'unit' => 'count'],
                'lightning_noise_count' => ['label' => 'Lightning Noise Count', 'unit' => 'count'],
            ],
        ],
        'derived_heat_stress' => [
            'enabled' => false,
            'metrics' => [
                'bgt' => ['label' => 'Black Globe Temperature', 'unit' => 'temperature'],
                'wbgt' => ['label' => 'Wet Bulb Globe Temperature', 'unit' => 'temperature'],
                'bgtbatt' => ['label' => 'BGT Battery', 'unit' => 'voltage'],
            ],
        ],
        'console_power' => [
            'enabled' => false,
            'metrics' => [
                'consoleext_batt' => ['label' => 'Console External Battery', 'unit' => 'voltage'],
                'consolebattp' => ['label' => 'Console Battery Percent', 'unit' => 'percent'],
                'consBatteryVoltage' => ['label' => 'Console Battery Voltage', 'unit' => 'voltage'],
                'referenceVoltage' => ['label' => 'Reference Voltage', 'unit' => 'voltage'],
                'supplyVoltage' => ['label' => 'Supply Voltage', 'unit' => 'voltage'],
            ],
        ],
        'soil_moisture' => [
            'enabled' => false,
            'metrics' => [
                'soilMoist1' => ['label' => 'Soil Moisture 1', 'unit' => 'percent'],
                'soilMoist2' => ['label' => 'Soil Moisture 2', 'unit' => 'percent'],
                'soilMoist3' => ['label' => 'Soil Moisture 3', 'unit' => 'percent'],
                'soilMoist4' => ['label' => 'Soil Moisture 4', 'unit' => 'percent'],
                'soilMoist5' => ['label' => 'Soil Moisture 5', 'unit' => 'percent'],
                'soilMoist6' => ['label' => 'Soil Moisture 6', 'unit' => 'percent'],
                'soilMoist7' => ['label' => 'Soil Moisture 7', 'unit' => 'percent'],
                'soilMoist8' => ['label' => 'Soil Moisture 8', 'unit' => 'percent'],
                'soilMoist9' => ['label' => 'Soil Moisture 9', 'unit' => 'percent'],
                'soilMoist10' => ['label' => 'Soil Moisture 10', 'unit' => 'percent'],
                'soilMoist11' => ['label' => 'Soil Moisture 11', 'unit' => 'percent'],
                'soilMoist12' => ['label' => 'Soil Moisture 12', 'unit' => 'percent'],
                'soilMoist13' => ['label' => 'Soil Moisture 13', 'unit' => 'percent'],
                'soilMoist14' => ['label' => 'Soil Moisture 14', 'unit' => 'percent'],
                'soilMoist15' => ['label' => 'Soil Moisture 15', 'unit' => 'percent'],
                'soilMoist16' => ['label' => 'Soil Moisture 16', 'unit' => 'percent'],
            ],
        ],
        'soil_temperature' => [
            'enabled' => false,
            'metrics' => [
                'soilTemp1' => ['label' => 'Soil Temperature 1', 'unit' => 'temperature'],
                'soilTemp2' => ['label' => 'Soil Temperature 2', 'unit' => 'temperature'],
                'soilTemp3' => ['label' => 'Soil Temperature 3', 'unit' => 'temperature'],
                'soilTemp4' => ['label' => 'Soil Temperature 4', 'unit' => 'temperature'],
                'soilTemp5' => ['label' => 'Soil Temperature 5', 'unit' => 'temperature'],
                'soilTemp6' => ['label' => 'Soil Temperature 6', 'unit' => 'temperature'],
                'soilTemp7' => ['label' => 'Soil Temperature 7', 'unit' => 'temperature'],
                'soilTemp8' => ['label' => 'Soil Temperature 8', 'unit' => 'temperature'],
                'soilmTemp1' => ['label' => 'Soilm Temperature 1', 'unit' => 'temperature'],
                'soilmTemp2' => ['label' => 'Soilm Temperature 2', 'unit' => 'temperature'],
                'soilmTemp3' => ['label' => 'Soilm Temperature 3', 'unit' => 'temperature'],
                'soilmTemp4' => ['label' => 'Soilm Temperature 4', 'unit' => 'temperature'],
                'soilmTemp5' => ['label' => 'Soilm Temperature 5', 'unit' => 'temperature'],
                'soilmTemp6' => ['label' => 'Soilm Temperature 6', 'unit' => 'temperature'],
                'soilmTemp7' => ['label' => 'Soilm Temperature 7', 'unit' => 'temperature'],
                'soilmTemp8' => ['label' => 'Soilm Temperature 8', 'unit' => 'temperature'],
                'soilmTemp9' => ['label' => 'Soilm Temperature 9', 'unit' => 'temperature'],
                'soilmTemp10' => ['label' => 'Soilm Temperature 10', 'unit' => 'temperature'],
                'soilmTemp11' => ['label' => 'Soilm Temperature 11', 'unit' => 'temperature'],
                'soilmTemp12' => ['label' => 'Soilm Temperature 12', 'unit' => 'temperature'],
                'soilmTemp13' => ['label' => 'Soilm Temperature 13', 'unit' => 'temperature'],
                'soilmTemp14' => ['label' => 'Soilm Temperature 14', 'unit' => 'temperature'],
                'soilmTemp15' => ['label' => 'Soilm Temperature 15', 'unit' => 'temperature'],
                'soilmTemp16' => ['label' => 'Soilm Temperature 16', 'unit' => 'temperature'],
            ],
        ],
        'soil_ec' => [
            'enabled' => false,
            'metrics' => [
                'soilEC1' => ['label' => 'Soil EC 1', 'unit' => 'usiecm'],
                'soilEC2' => ['label' => 'Soil EC 2', 'unit' => 'usiecm'],
                'soilEC3' => ['label' => 'Soil EC 3', 'unit' => 'usiecm'],
                'soilEC4' => ['label' => 'Soil EC 4', 'unit' => 'usiecm'],
                'soilEC5' => ['label' => 'Soil EC 5', 'unit' => 'usiecm'],
                'soilEC6' => ['label' => 'Soil EC 6', 'unit' => 'usiecm'],
                'soilEC7' => ['label' => 'Soil EC 7', 'unit' => 'usiecm'],
                'soilEC8' => ['label' => 'Soil EC 8', 'unit' => 'usiecm'],
                'soilEC9' => ['label' => 'Soil EC 9', 'unit' => 'usiecm'],
                'soilEC10' => ['label' => 'Soil EC 10', 'unit' => 'usiecm'],
                'soilEC11' => ['label' => 'Soil EC 11', 'unit' => 'usiecm'],
                'soilEC12' => ['label' => 'Soil EC 12', 'unit' => 'usiecm'],
                'soilEC13' => ['label' => 'Soil EC 13', 'unit' => 'usiecm'],
                'soilEC14' => ['label' => 'Soil EC 14', 'unit' => 'usiecm'],
                'soilEC15' => ['label' => 'Soil EC 15', 'unit' => 'usiecm'],
                'soilEC16' => ['label' => 'Soil EC 16', 'unit' => 'usiecm'],
            ],
        ],
        'lds01_level' => [
            'enabled' => false,
            'metrics' => [
                'air_ch1' => ['label' => 'LDS01 Air 1', 'unit' => 'mm'],
                'air_ch2' => ['label' => 'LDS01 Air 2', 'unit' => 'mm'],
                'depth_ch1' => ['label' => 'LDS01 Depth 1', 'unit' => 'mm'],
                'depth_ch2' => ['label' => 'LDS01 Depth 2', 'unit' => 'mm'],
                'thi_ch1' => ['label' => 'LDS01 THI 1', 'unit' => 'mm'],
                'thi_ch2' => ['label' => 'LDS01 THI 2', 'unit' => 'mm'],
                'ldsbatt1' => ['label' => 'LDS01 Batt 1', 'unit' => 'voltage'],
                'ldsbatt2' => ['label' => 'LDS01 Batt 2', 'unit' => 'voltage'],
                'ldsheat_ch1' => ['label' => 'LDS01 Heater 1', 'unit' => 'count'],
                'ldsheat_ch2' => ['label' => 'LDS01 Heater 2', 'unit' => 'count'],
            ],
        ],
    ],
    'field_map' => [
        'dateTime' => 'dateTime',
        'usUnits' => 'usUnits',
        'outTemp' => 'outTemp',
        'inTemp' => 'inTemp',
        'dewpoint' => 'dewpoint',
        'inDewpoint' => 'inDewpoint',
        'appTemp' => 'appTemp',
        'heatindex' => 'heatindex',
        'windchill' => 'windchill',
        'humidex' => 'humidex',
        'outHumidity' => 'outHumidity',
        'inHumidity' => 'inHumidity',
        'barometer' => 'barometer',
        'pressure' => 'pressure',
        'windSpeed' => 'windSpeed',
        'windGust' => 'windGust',
        'windDir' => 'windDir',
        'windrun' => 'windrun',
        'rainRate' => 'rainRate',
        'rain' => 'rain',
        'rainDur' => 'rainDur',
        'UV' => 'UV',
        'radiation' => 'radiation',
        'cloudbase' => 'cloudbase',
        'ET' => 'ET',
        'solarAltitude' => 'solarAltitude',
        'solarAzimuth' => 'solarAzimuth',
        'solarTime' => 'solarTime',
        'lunarAltitude' => 'lunarAltitude',
        'lunarAzimuth' => 'lunarAzimuth',
        'lunarTime' => 'lunarTime',
        'sunshineDur' => 'sunshineDur',
        'pm2_5' => 'pm2_5',
        'lightning_strike_count' => 'lightning_strike_count',
        'windBatteryStatus' => 'windBatteryStatus',
        'rainBatteryStatus' => 'rainBatteryStatus',
        'lightning_Batt' => 'lightning_Batt',
        'pm25_Batt1' => 'pm25_Batt1',
        'inTempBatteryStatus' => 'inTempBatteryStatus',
        'extraTemp1' => 'extraTemp1',
        'extraTemp2' => 'extraTemp2',
        'extraTemp3' => 'extraTemp3',
        'extraTemp4' => 'extraTemp4',
        'extraTemp5' => 'extraTemp5',
        'extraTemp6' => 'extraTemp6',
        'extraTemp7' => 'extraTemp7',
        'extraTemp8' => 'extraTemp8',
        'extraHumid1' => 'extraHumid1',
        'extraHumid2' => 'extraHumid2',
        'extraHumid3' => 'extraHumid3',
        'extraHumid4' => 'extraHumid4',
        'extraHumid5' => 'extraHumid5',
        'extraHumid6' => 'extraHumid6',
        'extraHumid7' => 'extraHumid7',
        'extraHumid8' => 'extraHumid8',
        'batteryStatus1' => 'batteryStatus1',
        'batteryStatus2' => 'batteryStatus2',
        'batteryStatus3' => 'batteryStatus3',
        'batteryStatus4' => 'batteryStatus4',
        'batteryStatus5' => 'batteryStatus5',
        'batteryStatus6' => 'batteryStatus6',
        'batteryStatus7' => 'batteryStatus7',
        'batteryStatus8' => 'batteryStatus8',
        'co2' => 'co2',
        'co2_Batt' => 'co2_Batt',
        'co2_Hum' => 'co2_Hum',
        'co2_Temp' => 'co2_Temp',
        'co2in' => 'co2in',
        'leafTemp1' => 'leafTemp1',
        'leafTemp2' => 'leafTemp2',
        'leafWet1' => 'leafWet1',
        'leafWet2' => 'leafWet2',
        'leafWet3' => 'leafWet3',
        'leafWet4' => 'leafWet4',
        'leafWet5' => 'leafWet5',
        'leafWet6' => 'leafWet6',
        'leafWet7' => 'leafWet7',
        'leafWet8' => 'leafWet8',
        'leafWetBatt1' => 'leafWetBatt1',
        'leafWetBatt2' => 'leafWetBatt2',
        'leafWetBatt3' => 'leafWetBatt3',
        'leafWetBatt4' => 'leafWetBatt4',
        'leafWetBatt5' => 'leafWetBatt5',
        'leafWetBatt6' => 'leafWetBatt6',
        'leafWetBatt7' => 'leafWetBatt7',
        'leafWetBatt8' => 'leafWetBatt8',
        'leak_1' => 'leak_1',
        'leak_2' => 'leak_2',
        'leak_3' => 'leak_3',
        'leak_4' => 'leak_4',
        'leak_Batt1' => 'leak_Batt1',
        'leak_Batt2' => 'leak_Batt2',
        'leak_Batt3' => 'leak_Batt3',
        'leak_Batt4' => 'leak_Batt4',
        'hail' => 'hail',
        'hailRate' => 'hailRate',
        'hailDur' => 'hailDur',
        'hailBatteryStatus' => 'hailBatteryStatus',
        'snow' => 'snow',
        'snowDepth' => 'snowDepth',
        'snowMoisture' => 'snowMoisture',
        'snowRate' => 'snowRate',
        'snowBatteryStatus' => 'snowBatteryStatus',
        'pm1_0' => 'pm1_0',
        'pm4_0' => 'pm4_0',
        'pm10_0' => 'pm10_0',
        'pm25_1' => 'pm25_1',
        'pm25_2' => 'pm25_2',
        'pm25_3' => 'pm25_3',
        'pm25_4' => 'pm25_4',
        'pm25_Batt2' => 'pm25_Batt2',
        'pm25_Batt3' => 'pm25_Batt3',
        'pm25_Batt4' => 'pm25_Batt4',
        'lightning_distance' => 'lightning_distance',
        'lightning_disturber_count' => 'lightning_disturber_count',
        'lightning_energy' => 'lightning_energy',
        'lightning_noise_count' => 'lightning_noise_count',
        'bgt' => 'bgt',
        'wbgt' => 'wbgt',
        'bgtbatt' => 'bgtbatt',
        'consoleext_batt' => 'consoleext_batt',
        'consolebattp' => 'consolebattp',
        'consBatteryVoltage' => 'consBatteryVoltage',
        'referenceVoltage' => 'referenceVoltage',
        'supplyVoltage' => 'supplyVoltage',
        'soilMoist1' => 'soilMoist1',
        'soilMoist2' => 'soilMoist2',
        'soilMoist3' => 'soilMoist3',
        'soilMoist4' => 'soilMoist4',
        'soilMoist5' => 'soilMoist5',
        'soilMoist6' => 'soilMoist6',
        'soilMoist7' => 'soilMoist7',
        'soilMoist8' => 'soilMoist8',
        'soilMoist9' => 'soilMoist9',
        'soilMoist10' => 'soilMoist10',
        'soilMoist11' => 'soilMoist11',
        'soilMoist12' => 'soilMoist12',
        'soilMoist13' => 'soilMoist13',
        'soilMoist14' => 'soilMoist14',
        'soilMoist15' => 'soilMoist15',
        'soilMoist16' => 'soilMoist16',
        'soilTemp1' => 'soilTemp1',
        'soilTemp2' => 'soilTemp2',
        'soilTemp3' => 'soilTemp3',
        'soilTemp4' => 'soilTemp4',
        'soilTemp5' => 'soilTemp5',
        'soilTemp6' => 'soilTemp6',
        'soilTemp7' => 'soilTemp7',
        'soilTemp8' => 'soilTemp8',
        'soilmTemp1' => 'soilmTemp1',
        'soilmTemp2' => 'soilmTemp2',
        'soilmTemp3' => 'soilmTemp3',
        'soilmTemp4' => 'soilmTemp4',
        'soilmTemp5' => 'soilmTemp5',
        'soilmTemp6' => 'soilmTemp6',
        'soilmTemp7' => 'soilmTemp7',
        'soilmTemp8' => 'soilmTemp8',
        'soilmTemp9' => 'soilmTemp9',
        'soilmTemp10' => 'soilmTemp10',
        'soilmTemp11' => 'soilmTemp11',
        'soilmTemp12' => 'soilmTemp12',
        'soilmTemp13' => 'soilmTemp13',
        'soilmTemp14' => 'soilmTemp14',
        'soilmTemp15' => 'soilmTemp15',
        'soilmTemp16' => 'soilmTemp16',
        'soilEC1' => 'soilEC1',
        'soilEC2' => 'soilEC2',
        'soilEC3' => 'soilEC3',
        'soilEC4' => 'soilEC4',
        'soilEC5' => 'soilEC5',
        'soilEC6' => 'soilEC6',
        'soilEC7' => 'soilEC7',
        'soilEC8' => 'soilEC8',
        'soilEC9' => 'soilEC9',
        'soilEC10' => 'soilEC10',
        'soilEC11' => 'soilEC11',
        'soilEC12' => 'soilEC12',
        'soilEC13' => 'soilEC13',
        'soilEC14' => 'soilEC14',
        'soilEC15' => 'soilEC15',
        'soilEC16' => 'soilEC16',
        'air_ch1' => 'air_ch1',
        'air_ch2' => 'air_ch2',
        'depth_ch1' => 'depth_ch1',
        'depth_ch2' => 'depth_ch2',
        'thi_ch1' => 'thi_ch1',
        'thi_ch2' => 'thi_ch2',
        'ldsbatt1' => 'ldsbatt1',
        'ldsbatt2' => 'ldsbatt2',
        'ldsheat_ch1' => 'ldsheat_ch1',
        'ldsheat_ch2' => 'ldsheat_ch2',
    ],
    'db' => [
        'host' => '127.0.0.1',
        'port' => '3306',
        'database' => 'weather',
        'username' => 'weather',
        'password' => 'CHANGE_ME',
    ],
    // Dedicated writer credentials for cron forecast cache refreshes.
    // Leave empty to fall back to the read-only `db` credentials.
    'forecast_writer_db' => [
        'host' => '127.0.0.1',
        'port' => '3306',
        'database' => 'weather',
        'username' => '',
        'password' => '',
    ],
    // Dedicated writer credentials for monthly history rollups.
    // Leave empty to fall back to forecast_writer_db or the read-only db block.
    'history_writer_db' => [
        'host' => '127.0.0.1',
        'port' => '3306',
        'database' => 'weather',
        'username' => '',
        'password' => '',
    ],
    'mqtt' => [
        'enabled' => true,
        // Keep false unless browser-side MQTT authentication is strictly required.
        'expose_password' => false,
        'url' => 'ws://127.0.0.1:9001/mqtt',
        'username' => 'CHANGE_ME',
        'password' => 'CHANGE_ME',
        'topic' => 'weewx/#',
    ],
    'api' => [
        // Harden dump endpoint by default while keeping it available.
        'dump_enabled' => true,
        'dump_default_rows' => 1000,
        'dump_max_rows' => 10000,
        // If set, /api/dump.php requires this token (GET token= or X-Api-Token header).
        'dump_token' => '',
    ],
    'history' => [
        'default_hours' => '24',
        'max_hours' => (string) (24 * 366),
        // Closed months can be stored here by the monthly rollup CLI job.
        'summary_table' => 'pws_history_monthly_summary',
        'lookback_years' => 3,
    ],
    'security' => [
        'enable_headers' => true,
        'content_security_policy' => "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; connect-src 'self' ws: wss: https:; font-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'self'",
        'referrer_policy' => 'strict-origin-when-cross-origin',
        'frame_options' => 'SAMEORIGIN',
        'permissions_policy' => 'geolocation=(), microphone=(), camera=()',
    ],
];
