<?php

declare(strict_types=1);

return [
    'paths' => [
        'base_dir' => '..',
        'src_dir' => 'src',
        'public_dir' => 'weewx/new',
        'docs_dir' => 'docs',
        'cache_dir' => 'var/cache/pws-live-site',
    ],
    'ui' => [
        'css_base' => 'assets/css/base.css',
        'css_themes' => [
            'bright' => 'assets/css/theme-bright.css',
            'dark' => 'assets/css/theme-dark.css',
        ],
        'default_theme' => 'bright',
        'css_custom' => '',
        'plotly_js' => 'assets/vendor/plotly-2.35.2.min.js',
        'plotly_wind_rose' => true,
        'graphs' => [
            'temp_outside' => true,
            'temp_inside' => true,
            'humidity_outside' => true,
            'humidity_inside' => true,
            'wind_speed' => true,
            'wind_direction' => true,
            'pressure' => true,
            'rain_rate_hourly' => true,
            'rain_total_duration' => true,
            'feels_like' => true,
            'solar' => true,
            'cloudbase' => true,
            'et' => true,
            'sunshine' => true,
            'windrun' => true,
            'pm25' => true,
            'lightning' => true,
            'wind_rose' => true,
            'battery_wind' => true,
            'battery_rain' => true,
            'battery_lightning' => true,
            'battery_pm25' => true,
            'battery_indoor' => true,
        ],
    ],
    'field_map' => [
        'dateTime' => 'dateTime',
        'usUnits' => 'usUnits',
        'outTemp' => 'outTemp',
        'inTemp' => 'inTemp',
        'dewpoint' => 'dewpoint',
        'inDewpoint' => 'inDewpoint',
        'appTemp' => 'appTemp',
        'heatindex' => 'heatindex',
        'windchill' => 'windchill',
        'humidex' => 'humidex',
        'outHumidity' => 'outHumidity',
        'inHumidity' => 'inHumidity',
        'barometer' => 'barometer',
        'pressure' => 'pressure',
        'windSpeed' => 'windSpeed',
        'windGust' => 'windGust',
        'windDir' => 'windDir',
        'windrun' => 'windrun',
        'rainRate' => 'rainRate',
        'rain' => 'rain',
        'rainDur' => 'rainDur',
        'UV' => 'UV',
        'radiation' => 'radiation',
        'cloudbase' => 'cloudbase',
        'ET' => 'ET',
        'solarAltitude' => 'solarAltitude',
        'sunshineDur' => 'sunshineDur',
        'pm2_5' => 'pm2_5',
        'lightning_strike_count' => 'lightning_strike_count',
        'windBatteryStatus' => 'windBatteryStatus',
        'rainBatteryStatus' => 'rainBatteryStatus',
        'lightning_Batt' => 'lightning_Batt',
        'pm25_Batt1' => 'pm25_Batt1',
        'inTempBatteryStatus' => 'inTempBatteryStatus',
    ],
    'db' => [
        'host' => '127.0.0.1',
        'port' => '3306',
        'database' => 'weather',
        'username' => 'weather',
        'password' => 'CHANGE_ME',
    ],
    'mqtt' => [
        'url' => 'ws://127.0.0.1:9001/mqtt',
        'username' => 'CHANGE_ME',
        'password' => 'CHANGE_ME',
        'topic' => 'weewx/#',
    ],
    'history' => [
        'default_hours' => '24',
        'max_hours' => (string) (24 * 366),
    ],
];
