<?php
declare(strict_types=1);
return [
    'nav' => ['dashboard' => 'Dashboard', 'trends' => 'Trends', 'history' => 'Verlauf', 'prediction' => 'Vorhersage', 'debug' => 'Debug'],
    'common' => ['theme' => 'Thema', 'language' => 'Sprache', 'loading' => 'Laden...', 'failed_load' => 'Laden fehlgeschlagen.', 'unavailable' => 'Nicht verfugbar', 'never' => 'nie', 'none' => 'keine', 'missing' => 'fehlt', 'n_a' => 'k. A.', 'day' => 'Tag', 'yes' => 'ja', 'no' => 'nein', 'status' => 'Status', 'local' => 'lokal'],
    'range' => ['today' => 'Heute', 'yesterday' => 'Gestern', 'week' => 'Letzte Woche', 'month' => 'Letzter Monat', 'year' => 'Letztes Jahr'],
    'status' => ['last_update' => 'Letztes Update', 'range' => 'Bereich', 'window' => 'Fenster', 'updated' => 'Aktualisiert', 'provider' => 'Provider', 'hourly_cache' => 'Stunden-Cache', 'daily_cache' => 'Tages-Cache', 'run' => 'Lauf', 'generated' => 'Erstellt', 'headers' => 'Header'],
    'dashboard' => ['page_title' => 'PWS Live Dashboard', 'current_weather' => 'Aktuelles Wetter', 'forecast_provider_pending' => 'Forecast-Provider: ausstehend', 'next_5_hours' => 'Nachste 5 Stunden', 'five_day_forecast' => '5-Tage-Vorhersage', 'sun_moon' => 'Sonne & Mond', 'wind' => 'Wind', 'wind_rose' => 'Windrose (Richtung x Geschwindigkeitsklasse)', 'weather_graphs' => 'Wetterdiagramme', 'environment_graphs' => 'Umweltsensor-Diagramme', 'battery_graphs' => 'Batteriediagramme', 'temp_group' => 'Temp', 'humidity_group' => 'Feuchtigkeit', 'rain_group' => 'Regen', 'sun_sky_group' => 'Sonne / Himmel', 'wind_group' => 'Wind', 'pressure_group' => 'Druck', 'air_quality_group' => 'Luftqualitat', 'lightning_group' => 'Blitze', 'power_battery_group' => 'Strom / Batterie', 'other_sensors' => 'Weitere Sensoren'],
    'forecast' => ['page_title' => 'PWS Forecast', 'title' => 'Vorhersage', 'next_hours' => 'Nachste Stunden', 'daily_forecast' => 'Tagesvorhersage', 'no_hourly_cache' => 'Keine Stundenvorhersage im Cache.', 'no_daily_cache' => 'Keine Tagesvorhersage im Cache.', 'failed_cache' => 'Forecast-Cache konnte nicht geladen werden.', 'rain_chance' => 'Regenwahrscheinlichkeit {value}', 'high_low' => 'Hoch {high} / Tief {low}'],
    'trends' => ['page_title' => 'PWS Trends', 'title' => 'Trend-Nowcast', 'rain_likelihood' => 'Regenwahrscheinlichkeit', 'trend_details' => 'Trenddetails', 'summary' => 'Zusammenfassung', 'metric' => 'Messwert', 'current' => 'Aktuell', 'direction' => 'Richtung', 'slope_per_hour' => 'Steigung pro Stunde', 'prediction' => 'Vorhersage', 'confidence' => 'Vertrauen', 'samples' => 'Werte', 'unavailable' => 'Nicht verfugbar', 'no_rain_indicators' => 'Derzeit keine starken Regenindikatoren.', 'failed_load' => 'Trends konnten nicht geladen werden.', 'rising' => 'steigend', 'falling' => 'fallend', 'steady' => 'stabil'],
    'prediction' => ['page_title' => 'PWS Prediction', 'title' => 'Vorhersage', 'by_hour' => 'Vorhersage pro Stunde', 'no_rows' => 'Keine Vorhersagezeilen verfugbar.'],
    'history' => ['page_title' => 'Monatsverlauf', 'title' => 'Monatliche Hoch / Mittel / Tief Historie', 'note' => 'Monatliche Hoch-/Mittel-/Tiefwerte pro Messwert (Jan-Dez Spalten, letzte {years} Jahre) mit gecachten abgeschlossenen Monaten plus live archive_day_* Daten fur den aktuellen Monat.', 'failed_load' => 'Historie konnte nicht geladen werden: {error}', 'no_sections' => 'Keine monatlichen Verlaufsabschnitte fur die aktuelle Feldzuordnung verfugbar.', 'year_type' => 'Jahr / Typ', 'high' => 'Hoch', 'average' => 'Mittel', 'low' => 'Tief', 'months_short' => ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dez']],
    'debug' => ['page_title' => 'PWS Debug', 'title' => 'Debug / Admin'],
];
