<?php
declare(strict_types=1);
return [
    'nav' => ['dashboard' => 'Panel', 'trends' => 'Tendencias', 'history' => 'Historial', 'prediction' => 'Prediccion', 'debug' => 'Debug'],
    'common' => ['theme' => 'Tema', 'language' => 'Idioma', 'loading' => 'Cargando...', 'failed_load' => 'Error al cargar.', 'unavailable' => 'No disponible', 'never' => 'nunca', 'none' => 'ninguno', 'missing' => 'ausente', 'n_a' => 'n/d', 'day' => 'Dia', 'yes' => 'si', 'no' => 'no', 'status' => 'Estado', 'local' => 'local'],
    'range' => ['today' => 'Hoy', 'yesterday' => 'Ayer', 'week' => 'Ultima semana', 'month' => 'Ultimo mes', 'year' => 'Ultimo ano'],
    'status' => ['last_update' => 'Ultima actualizacion', 'range' => 'Rango', 'window' => 'Ventana', 'updated' => 'Actualizado', 'provider' => 'Proveedor', 'hourly_cache' => 'Cache horario', 'daily_cache' => 'Cache diario', 'run' => 'Ejecucion', 'generated' => 'Generado', 'headers' => 'Cabeceras'],
    'dashboard' => ['page_title' => 'PWS Live Dashboard', 'current_weather' => 'Tiempo actual', 'forecast_provider_pending' => 'Proveedor de pronostico: pendiente', 'next_5_hours' => 'Proximas 5 horas', 'five_day_forecast' => 'Pronostico de 5 dias', 'sun_moon' => 'Sol y Luna', 'wind' => 'Viento', 'wind_rose' => 'Rosa de los vientos (direccion x clase de velocidad)', 'weather_graphs' => 'Graficas meteorologicas', 'environment_graphs' => 'Graficas de sensores ambientales', 'battery_graphs' => 'Graficas de bateria', 'temp_group' => 'Temp', 'humidity_group' => 'Humedad', 'rain_group' => 'Lluvia', 'sun_sky_group' => 'Sol / Cielo', 'wind_group' => 'Viento', 'pressure_group' => 'Presion', 'air_quality_group' => 'Calidad del aire', 'lightning_group' => 'Rayos', 'power_battery_group' => 'Energia / Bateria', 'other_sensors' => 'Otros sensores'],
    'forecast' => ['page_title' => 'PWS Forecast', 'title' => 'Pronostico', 'next_hours' => 'Proximas horas', 'daily_forecast' => 'Pronostico diario', 'no_hourly_cache' => 'No hay pronostico horario en cache.', 'no_daily_cache' => 'No hay pronostico diario en cache.', 'failed_cache' => 'Error al cargar la cache del pronostico.', 'rain_chance' => 'Probabilidad de lluvia {value}', 'high_low' => 'Max {high} / Min {low}'],
    'trends' => ['page_title' => 'PWS Trends', 'title' => 'Nowcast de tendencias', 'rain_likelihood' => 'Probabilidad de lluvia', 'trend_details' => 'Detalles de tendencia', 'summary' => 'Resumen', 'metric' => 'Metrica', 'current' => 'Actual', 'direction' => 'Direccion', 'slope_per_hour' => 'Pendiente por hora', 'prediction' => 'Prediccion', 'confidence' => 'Confianza', 'samples' => 'Muestras', 'unavailable' => 'No disponible', 'no_rain_indicators' => 'No hay indicadores fuertes de lluvia en este momento.', 'failed_load' => 'Error al cargar las tendencias.', 'rising' => 'subiendo', 'falling' => 'bajando', 'steady' => 'estable'],
    'prediction' => ['page_title' => 'PWS Prediction', 'title' => 'Prediccion', 'by_hour' => 'Prediccion por hora', 'no_rows' => 'No hay filas de prediccion disponibles.'],
    'history' => ['page_title' => 'Historial mensual', 'title' => 'Historial mensual Max / Prom / Min', 'note' => 'Max/prom/min mensuales por metrica (columnas ene-dic, ultimos {years} anos) usando meses cerrados en cache mas datos archive_day_* en vivo para el mes actual.', 'failed_load' => 'Error al cargar el historial: {error}', 'no_sections' => 'No hay secciones de historial mensual disponibles para el mapeo actual.', 'year_type' => 'Ano / Tipo', 'high' => 'Max', 'average' => 'Promedio', 'low' => 'Min', 'months_short' => ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic']],
    'debug' => ['page_title' => 'PWS Debug', 'title' => 'Debug / Admin'],
];
