<?php
declare(strict_types=1);
return [
    'nav' => ['dashboard' => 'Tableau de bord', 'trends' => 'Tendances', 'history' => 'Historique', 'prediction' => 'Prediction', 'debug' => 'Debug'],
    'common' => ['theme' => 'Theme', 'language' => 'Langue', 'loading' => 'Chargement...', 'failed_load' => 'Echec du chargement.', 'unavailable' => 'Indisponible', 'never' => 'jamais', 'none' => 'aucun', 'missing' => 'absent', 'n_a' => 'n/d', 'day' => 'Jour', 'yes' => 'oui', 'no' => 'non', 'status' => 'Statut', 'local' => 'local'],
    'range' => ['today' => "Aujourd'hui", 'yesterday' => 'Hier', 'week' => 'Semaine derniere', 'month' => 'Mois dernier', 'year' => 'Annee derniere'],
    'status' => ['last_update' => 'Derniere mise a jour', 'range' => 'Plage', 'window' => 'Fenetre', 'updated' => 'Mis a jour', 'provider' => 'Fournisseur', 'hourly_cache' => 'Cache horaire', 'daily_cache' => 'Cache journalier', 'run' => 'Execution', 'generated' => 'Genere', 'headers' => 'En-tetes'],
    'dashboard' => ['page_title' => 'PWS Live Dashboard', 'current_weather' => 'Conditions actuelles', 'forecast_provider_pending' => 'Fournisseur de prevision: en attente', 'next_5_hours' => '5 prochaines heures', 'five_day_forecast' => 'Prevision sur 5 jours', 'sun_moon' => 'Soleil & Lune', 'wind' => 'Vent', 'wind_rose' => 'Rose des vents (direction x classe de vitesse)', 'weather_graphs' => 'Graphiques meteo', 'environment_graphs' => "Graphiques des capteurs d'environnement", 'battery_graphs' => 'Graphiques batterie', 'temp_group' => 'Temp', 'humidity_group' => 'Humidite', 'rain_group' => 'Pluie', 'sun_sky_group' => 'Soleil / Ciel', 'wind_group' => 'Vent', 'pressure_group' => 'Pression', 'air_quality_group' => 'Qualite de l’air', 'lightning_group' => 'Foudre', 'power_battery_group' => 'Alimentation / Batterie', 'other_sensors' => 'Autres capteurs'],
    'forecast' => ['page_title' => 'PWS Forecast', 'title' => 'Prevision', 'next_hours' => 'Prochaines heures', 'daily_forecast' => 'Prevision journaliere', 'no_hourly_cache' => 'Aucune prevision horaire en cache.', 'no_daily_cache' => 'Aucune prevision journaliere en cache.', 'failed_cache' => 'Echec du chargement du cache de prevision.', 'rain_chance' => 'Risque de pluie {value}', 'high_low' => 'Max {high} / Min {low}'],
    'trends' => ['page_title' => 'PWS Trends', 'title' => 'Nowcast de tendance', 'rain_likelihood' => 'Probabilite de pluie', 'trend_details' => 'Details de tendance', 'summary' => 'Resume', 'metric' => 'Mesure', 'current' => 'Actuel', 'direction' => 'Direction', 'slope_per_hour' => 'Pente par heure', 'prediction' => 'Prediction', 'confidence' => 'Confiance', 'samples' => 'Echantillons', 'unavailable' => 'Indisponible', 'no_rain_indicators' => "Aucun indicateur de pluie fort pour le moment.", 'failed_load' => 'Echec du chargement des tendances.', 'rising' => 'en hausse', 'falling' => 'en baisse', 'steady' => 'stable'],
    'prediction' => ['page_title' => 'PWS Prediction', 'title' => 'Prediction', 'by_hour' => 'Prediction par heure', 'no_rows' => 'Aucune ligne de prediction disponible.'],
    'history' => ['page_title' => 'Historique mensuel', 'title' => 'Historique mensuel Max / Moy / Min', 'note' => 'Max/moy/min mensuels par mesure (colonnes jan-dec, {years} dernieres annees) avec les mois clos en cache et les donnees archive_day_* en direct pour le mois courant.', 'failed_load' => "Echec du chargement de l'historique: {error}", 'no_sections' => "Aucune section d'historique mensuel disponible pour le mappage actuel.", 'year_type' => 'Annee / Type', 'high' => 'Max', 'average' => 'Moy', 'low' => 'Min', 'months_short' => ['Jan', 'Fev', 'Mar', 'Avr', 'Mai', 'Jun', 'Jul', 'Aou', 'Sep', 'Oct', 'Nov', 'Dec']],
    'debug' => ['page_title' => 'PWS Debug', 'title' => 'Debug / Admin'],
];
